### ISSUE TITLE
geodesy package cannot be installed

### ISSUE THREAD

**Issue by teguhpurnama** [MITeaps/pyinsar#1]
Hi Cody and Victor,

I tried to install this package but always failed when installing the dependency (geodesy package). I put the error message on the end of this message. Googling the workaround suggest me to install the geodesy package from github (pip install git+git://github.com/xolive/geodesy.git), but this also failed during compilation. Is there any other way to solve this problem?

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\teguh\anaconda3\envs\python38\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\teguh\\AppData\\Local\\Temp\\pip-install-k9nxvnf7\\geodesy_702f9629224044a18cb6970610d8f469\\setup.py'"'"'; __file__='"'"'C:\\Users\\teguh\\AppData\\Local\\Temp\\pip-install-k9nxvnf7\\geodesy_702f9629224044a18cb6970610d8f469\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\teguh\AppData\Local\Temp\pip-pip-egg-info-7spg07w0'
         cwd: C:\Users\teguh\AppData\Local\Temp\pip-install-k9nxvnf7\geodesy_702f9629224044a18cb6970610d8f469\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\teguh\AppData\Local\Temp\pip-install-k9nxvnf7\geodesy_702f9629224044a18cb6970610d8f469\setup.py", line 38, in <module>
        ext_modules=cythonize(extensions),
      File "C:\Users\teguh\anaconda3\envs\python38\lib\site-packages\Cython\Build\Dependencies.py", line 966, in cythonize
        module_list, module_metadata = create_extension_list(
      File "C:\Users\teguh\anaconda3\envs\python38\lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "C:\Users\teguh\anaconda3\envs\python38\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'geodesy/sphere.pyx' doesn't match any files

**Comment by CodyRude** [comment]
Hello,
I don't work on this project anymore, but it looks like you figured out it's an issue with a dependency of this project, the [geodesy package](https://github.com/xoolive/geodesy/issues/6). Since it seems the geodesy package wasn't tested on Windows, and we didn't run it on Windows, you might have more luck trying it in Linux.
